const menu = [
	{
		id: 1,
		title: 'Buttermilk Pancakes',
		category: 'Breakfast',
		price: 15.99,
		img: './images/item-1.jpeg',
		desc: 'Fluffy buttermilk pancakes served with maple syrup and a dollop of fresh whipped cream. A classic breakfast favorite.',
	},
	{
		id: 2,
		title: 'Diner Double',
		category: 'Lunch',
		price: 13.99,
		img: './images/item-2.jpeg',
		desc: 'A hearty double cheeseburger with perfectly seasoned beef patties, fresh lettuce, tomatoes, and a side of crispy fries.',
	},
	{
		id: 3,
		title: 'Chocolate Milkshake',
		category: 'Shakes',
		price: 6.99,
		img: './images/item-3.jpeg',
		desc: 'Indulge in a rich and creamy chocolate milkshake made with premium chocolate ice cream and topped with chocolate shavings.',
	},
	{
		id: 4,
		title: 'Country Delight',
		category: 'Breakfast',
		price: 20.99,
		img: './images/item-4.jpeg',
		desc: 'Start your day with our hearty Country Delight breakfast, featuring fluffy scrambled eggs, crispy bacon, and buttery toast.',
	},
	{
		id: 5,
		title: 'Egg Attack',
		category: 'Lunch',
		price: 22.99,
		img: './images/item-5.jpeg',
		desc: 'A delicious egg sandwich with perfectly cooked eggs, fresh vegetables, and your choice of condiments, all served on a warm bun.',
	},
	{
		id: 6,
		title: 'Oreo Dream',
		category: 'Shakes',
		price: 18.99,
		img: './images/item-6.jpeg',
		desc: 'Satisfy your sweet tooth with the Oreo Dream milkshake, made with real Oreos and vanilla ice cream, topped with whipped cream.',
	},
	{
		id: 7,
		title: 'Bacon Overflow',
		category: 'Breakfast',
		price: 8.99,
		img: './images/item-7.jpeg',
		desc: 'A breakfast classic with a twist – crispy bacon, fluffy scrambled eggs, and a drizzle of savory cheese sauce.',
	},
	{
		id: 8,
		title: 'American Classic',
		category: 'Lunch',
		price: 12.99,
		img: './images/item-8.jpeg',
		desc: 'Experience the American Classic burger, featuring a juicy beef patty, fresh lettuce, tomatoes, and all the fixings in a soft bun.',
	},
	{
		id: 9,
		title: 'Quarantine Buddy',
		category: 'Shakes',
		price: 16.99,
		img: './images/item-9.jpeg',
		desc: 'Stay refreshed with the Quarantine Buddy shake, a delightful blend of tropical fruits, yogurt, and a hint of coconut.',
	},
	{
		id: 10,
		title: 'Bison Steak',
		category: 'Dinner',
		price: 22.99,
		img: './images/item-10.jpeg',
		desc: 'Indulge in a tender and flavorful bison steak, grilled to perfection and served with a side of seasonal vegetables and garlic mashed potatoes.',
	},
];

export default menu;
